// Blue Salon storefront sample data (fictional listings, real brand names).
// Product imagery comes from the local /images folder — evening gowns and
// fine fashion jewellery, shot on white. Every product carries a gallery
// (images[]), colorHex swatch, editorial copy and spec details.
window.BS_DATA = (function () {
  const img = (file) => "images/" + file;

  const products = [
    { id: "zm-ivory-gown", vendor: "Zuhair Murad", name: "Crystal-Embellished Strapless Crepe Gown, Ivory",
      price: 28500, image: img("0_4d42c2f7-3d94-4330-8d41-384bbf740c8a_540x.webp"),
      badge: "New", badgeTone: "new", cat: "Gowns", type: "Evening", rating: 4.9, count: 14,
      color: "Ivory", colorHex: "#f1e9dc", sizes: ["6", "8", "10", "12"],
      images: [img("0_4d42c2f7-3d94-4330-8d41-384bbf740c8a_540x.webp")],
      desc: "Couture drama in ivory crepe — a strapless column scattered with hand-applied crystal motifs, gathered at the hip and split to the thigh. From the house that dresses the red carpet, made for the season's grandest invitations.",
      details: ["Stretch crepe · hand-applied crystals", "Strapless sweetheart bodice · boned", "Draped hip detail · front slit", "Concealed back zip", "Dry clean only", "Made in Lebanon"] },

    { id: "eliesaab-noir-gown", vendor: "Elie Saab", name: "Crystal Cascade Slip Gown, Noir",
      price: 19900, compareAt: 24900, badge: "-20%", badgeTone: "sale",
      image: img("0_72ed2cb0-f6df-46e1-aa85-33a64132db13_540x.webp"),
      cat: "Gowns", type: "Evening", rating: 4.8, count: 21,
      color: "Black", colorHex: "#1a1a1c", sizes: ["6", "8", "10", "12"],
      images: [img("0_72ed2cb0-f6df-46e1-aa85-33a64132db13_540x.webp")],
      desc: "A bias-cut column in inky cady, its neckline traced with a cascade of gold-set crystals. Quiet from afar, dazzling up close — evening dressing the Elie Saab way.",
      details: ["Silk-blend cady · bias cut", "Gold-set crystal cascade neckline", "Adjustable straps · low back", "Floor length · small train", "Dry clean only", "Made in Lebanon"] },

    { id: "leolin-dress", vendor: "Leo Lin", name: "Matilda Embroidered Tulle Gown — Blush Botanical",
      price: 2990, image: img("1_cbff2b7e-d52a-46e0-a986-89ed7f0083c9_540x.webp"),
      cat: "Gowns", type: "Evening", rating: 4.6, count: 22,
      color: "Blush", colorHex: "#e3c4bc", sizes: ["6", "8", "10", "12"],
      images: [img("1_cbff2b7e-d52a-46e0-a986-89ed7f0083c9_540x.webp")],
      desc: "Blouson sleeves and a sweeping column of embroidered tulle, blooming with blush botanicals and sequin light. Romantic, covered and made for warm-weather celebrations.",
      details: ["Embroidered tulle · sequin details", "Plunge V-neck · blouson sleeves", "Fully lined bodice and skirt", "Concealed back zip", "Dry clean only", "Designed in Australia"] },

    { id: "zm-gold-gown", vendor: "Zuhair Murad", name: "Sequin-Embellished Tulle Gown, Champagne Gold",
      price: 32000, badge: "Exclusive", badgeTone: "gold",
      image: img("1_d90af013-05a4-447c-b48b-e2f61584c227_540x.webp"),
      cat: "Gowns", type: "Evening", rating: 5, count: 9,
      color: "Gold", colorHex: "#c9a35e", sizes: ["6", "8", "10", "12"],
      images: [img("1_d90af013-05a4-447c-b48b-e2f61584c227_540x.webp")],
      desc: "Champagne-gold tulle worked entirely by hand with feathered sequin embroidery — a strapless ballgown that catches every light in the room. A Blue Salon exclusive for Qatar.",
      details: ["Hand-embroidered sequins on tulle", "Strapless corseted bodice", "Full A-line skirt · layered tulle", "Concealed back zip", "Blue Salon exclusive", "Made in Lebanon"] },

    { id: "swk-dazzling-swan", vendor: "Swarovski", name: "Dazzling Swan Bracelet, Rose-Gold Tone",
      price: 620, image: img("SWK128ACC04863_540x.webp"),
      cat: "Jewellery", type: "Bracelets", rating: 4.7, count: 118,
      color: "Rose gold", colorHex: "#d9a08c", sizes: ["OS"],
      images: [img("SWK128ACC04863_540x.webp")],
      desc: "The house swan, dazzling in pavé. A delicate rose-gold-tone chain carries the pink-crystal swan between sparkling stations — the everyday piece that never reads everyday.",
      details: ["Polished rose-tone finish", "Pavé crystal swan motif", "Lobster clasp · adjustable", "Length 17.5 cm", "Presented in Swarovski gift box"] },

    { id: "swk-sparkling-dance-set", vendor: "Swarovski", name: "Sparkling Dance Clover Set, Pink & Rose-Gold",
      price: 990, badge: "New", badgeTone: "new",
      image: img("SWK128ACC05524-3_540x.webp"),
      cat: "Jewellery", type: "Sets", rating: 4.8, count: 64,
      color: "Rose gold", colorHex: "#d9a08c", sizes: ["OS"],
      images: [img("SWK128ACC05524-3_540x.webp")],
      desc: "The signature Sparkling Dance stone — cut to tremble with every movement — set as a clover in pink crystal. Necklace and matching stud earrings, gift-ready in one box.",
      details: ["Necklace + stud earrings set", "Dancing crystal clover motif", "Polished rose-tone finish", "Necklace 38 cm + extender", "Presented in Swarovski gift box"] },

    { id: "lucabarra-heart-necklace", vendor: "Luca Barra", name: "Steel Necklace with Hearts & Pink Crystal",
      price: 240, soldOut: true,
      image: img("Luca_Barra_women_steel_necklace_with_pink_and_silver_hearts_and_crystal_CK2076-1_540x.webp"),
      cat: "Jewellery", type: "Necklaces", rating: 4.3, count: 37,
      color: "Silver", colorHex: "#cfd4da", sizes: ["OS"],
      images: [img("Luca_Barra_women_steel_necklace_with_pink_and_silver_hearts_and_crystal_CK2076-1_540x.webp")],
      desc: "A line of polished steel hearts descending to a single pink crystal heart. Light, playful and hypoallergenic — Italian fashion jewellery made for every day.",
      details: ["Polished stainless steel", "Pink crystal heart pendant", "Length 42 cm + 5 cm extender", "Hypoallergenic · nickel safe", "Made in Italy"] },

    { id: "lucabarra-flower-necklace", vendor: "Luca Barra", name: "Steel Necklace with Purple Zircon Flower",
      price: 260, image: img("Luca_Barra_women_steel_necklace_with_purple_zircon_flower_pendant_CK2195-1_540x.webp"),
      cat: "Jewellery", type: "Necklaces", rating: 4.4, count: 29,
      color: "Purple", colorHex: "#a678b8", sizes: ["OS"],
      images: [img("Luca_Barra_women_steel_necklace_with_purple_zircon_flower_pendant_CK2195-1_540x.webp")],
      desc: "A blossom of purple zircons on a whisper-fine steel chain, flanked by two floating crystals. Delicate colour that layers beautifully with everything.",
      details: ["Polished stainless steel", "Purple zircon flower pendant", "Two floating crystal stations", "Length 42 cm + 5 cm extender", "Made in Italy"] },

    { id: "cerruti-c-set", vendor: "Cerruti 1881", name: "Mother-of-Pearl 'C' Necklace, Earrings & Bracelet Set",
      price: 850, image: img("Full_Set_Overview_-CIJLN0013001-SET3_540x.webp"),
      cat: "Jewellery", type: "Sets", rating: 4.5, count: 42,
      color: "Gold", colorHex: "#d4af37", sizes: ["OS"],
      images: [img("Full_Set_Overview_-CIJLN0013001-SET3_540x.webp")],
      desc: "The maison's crystal-edged 'C' cradling a dome of mother-of-pearl — repeated across necklace, studs and station bracelet. A complete parure, gift-ready.",
      details: ["Necklace + earrings + bracelet", "Gold-tone plating · crystals", "Mother-of-pearl centre stones", "Necklace 42 cm · bracelet adjustable", "Presented in Cerruti 1881 gift box"] },

    { id: "justcavalli-earrings", vendor: "Just Cavalli", name: "Signature Chain Drop Earrings, Gold Tone",
      price: 380, compareAt: 475, badge: "-20%", badgeTone: "sale",
      image: img("JCA120ACC01009_2_copy_540x.webp"),
      cat: "Jewellery", type: "Earrings", rating: 4.2, count: 18,
      color: "Gold", colorHex: "#d4af37", sizes: ["OS"],
      images: [img("JCA120ACC01009_2_copy_540x.webp")],
      desc: "Mismatched by design — a pavé stud and a crystal heart, each trailing a fine chain finished with the Cavalli signature and a molten drop. Attitude, in gold tone.",
      details: ["Asymmetric pair · gold tone", "Pavé crystal studs", "Signature + drop pendants", "Butterfly fastening", "Presented in Just Cavalli pouch"] },

    { id: "fossil-star-bracelet", vendor: "Fossil", name: "Howlite Beaded Star Bolo Bracelet",
      price: 195, image: img("JF03115710-33_540x.webp"),
      cat: "Jewellery", type: "Bracelets", rating: 4.6, count: 83,
      color: "Ivory", colorHex: "#f1e9dc", sizes: ["OS"],
      images: [img("JF03115710-33_540x.webp")],
      desc: "White howlite beads on a grey cord, centred with a tiny gold-tone star and finished with a sliding bolo closure — stackable, adjustable, endlessly easy.",
      details: ["White howlite beads", "Gold-tone star centre", "Sliding bolo closure · adjustable", "Grey woven cord", "Fossil-branded keepsake tin"] },

    { id: "lesnereides-ring", vendor: "Les Néréides", name: "Cherry Blossom & Pink Stone Adjustable Ring",
      price: 425, badge: "Exclusive", badgeTone: "gold",
      image: img("ATBP604-1_540x.webp"),
      cat: "Jewellery", type: "Rings", rating: 4.7, count: 26,
      color: "Gold", colorHex: "#d4af37", sizes: ["OS"],
      images: [img("ATBP604-1_540x.webp")],
      desc: "Hand-enamelled cherry blossoms wrap the finger toward a faceted rose stone — Parisian storybook jewellery, finished in 14-carat gold plating and signed on the band.",
      details: ["Hand-enamelled blossom motifs", "Faceted rose-pink stone", "14-carat gold plating", "Adjustable open band", "Handmade in France"] },
    { id: "iceplay-runner-sneaker", vendor: "Ice Play", name: "Mesh Runner Sneaker, White & Silver",
      price: 690, badge: "New", badgeTone: "new",
      image: img("ICP123SHO00031_540x.webp"),
      cat: "Footwear", type: "Sneakers", rating: 4.5, count: 31,
      color: "White", colorHex: "#f6f5f1", sizes: ["36", "37", "38", "39", "40"],
      images: [img("ICP123SHO00031_540x.webp")],
      desc: "A clean white runner with mesh panels, silver trim and a graphic platform sole. Easy polish for travel days, weekend edits and pared-back tailoring.",
      details: ["Mesh and leather upper", "Silver heel and side trim", "Lace-up fastening", "Cushioned platform sole", "Rubber tread", "Made for everyday wear"] },

    { id: "lancel-pink-handle-bag", vendor: "Lancel", name: "Leather Top Handle Bag, Pink & Natural",
      price: 1890, badge: "New", badgeTone: "new",
      image: img("LNL123BAG00079_1_540x.webp"),
      cat: "Bags", type: "Handbags", rating: 4.8, count: 19,
      color: "Pink", colorHex: "#e94d98", sizes: ["OS"],
      images: [img("LNL123BAG00079_1_540x.webp")],
      desc: "A structured top-handle bag in confident pink leather, framed with natural tan trims and a detachable striped strap for hands-free styling.",
      details: ["Smooth leather body", "Top handles and detachable strap", "Zip side details", "Structured silhouette", "Internal slip pocket", "Presented with dust bag"] },

    { id: "orlandi-burgundy-braided-tote", vendor: "Orlandi Valentino", name: "Leather Braided Handle Tote, Burgundy",
      price: 1450,
      image: img("Orlandi_Valentino_Women_s_Leather_Braided_Handle_Tote_burgundy_angled_side_POV123BAG00286_1_540x.webp"),
      cat: "Bags", type: "Totes", rating: 4.6, count: 24,
      color: "Burgundy", colorHex: "#5a1724", sizes: ["OS"],
      images: [img("Orlandi_Valentino_Women_s_Leather_Braided_Handle_Tote_burgundy_angled_side_POV123BAG00286_1_540x.webp")],
      desc: "A soft burgundy leather tote with braided handles, folded side tabs and a long tassel pull. Rich colour, generous shape, quietly distinctive.",
      details: ["Leather outer", "Braided top handles", "Tassel detail", "Open tote shape", "Removable pouch detail", "Dust bag included"] },

    { id: "orlandi-black-shoulder-tote", vendor: "Orlandi Valentino", name: "Leather Shoulder Tote, Black",
      price: 1390,
      image: img("POV123BAG00290_1_540x.webp"),
      cat: "Bags", type: "Totes", rating: 4.5, count: 28,
      color: "Black", colorHex: "#090a0d", sizes: ["OS"],
      images: [img("POV123BAG00290_1_540x.webp")],
      desc: "A black leather shoulder tote with a polished circular fastening and clean architectural profile. Designed for office days and city evenings.",
      details: ["Smooth leather", "Dual shoulder handles", "Circular front hardware", "Structured base", "Zip compartment", "Dust bag included"] },

    { id: "schutz-patent-ankle-boot", vendor: "Schutz", name: "Patent Leather Ankle Boot, Oxblood",
      price: 980, compareAt: 1225, badge: "-20%", badgeTone: "sale",
      image: img("S2214700060002_02_540x.webp"),
      cat: "Footwear", type: "Boots", rating: 4.7, count: 34,
      color: "Oxblood", colorHex: "#651015", sizes: ["36", "37", "38", "39", "40"],
      images: [img("S2214700060002_02_540x.webp")],
      desc: "A glossy oxblood ankle boot with a sharp pointed toe and covered block heel. A high-impact finish for long dresses, denim and evening tailoring.",
      details: ["Patent leather upper", "Pointed toe", "Side zip fastening", "Covered block heel", "Leather lining", "Rubber-insert sole"] },

    { id: "schutz-black-ankle-sandal", vendor: "Schutz", name: "Ankle Strap Sandal, Black",
      price: 790,
      image: img("SHU123SHO01045_1_540x.webp"),
      cat: "Footwear", type: "Sandals", rating: 4.6, count: 41,
      color: "Black", colorHex: "#090a0d", sizes: ["36", "37", "38", "39", "40"],
      images: [img("SHU123SHO01045_1_540x.webp")],
      desc: "A minimal black ankle-strap sandal with a slim front band and refined high heel. The evening shoe that works across nearly every silhouette.",
      details: ["Leather upper", "Slim toe strap", "Adjustable ankle strap", "Stiletto heel", "Padded leather footbed", "Leather sole"] },

    { id: "godiva-centennial-chocolate-box", vendor: "Godiva", name: "Centennial Collection Chocolate Box",
      price: 220, badge: "New", badgeTone: "new",
      image: img("1782909937961.jpeg"),
      cat: "Gourmet", type: "Chocolates", rating: 4.9, count: 76,
      color: "Pink", colorHex: "#efb6c7", sizes: ["OS"],
      images: [img("1782909937961.jpeg")],
      desc: "A celebratory Godiva chocolate collection presented in a soft pink centennial box, with heritage pieces selected for gifting and after-dinner service.",
      details: ["Assorted Belgian chocolates", "Centennial edition packaging", "Milk, dark and white chocolate pieces", "Gift-ready presentation", "Store in a cool, dry place"] },

    { id: "moschino-baby-logo-set", vendor: "Moschino Baby", name: "Logo T-Shirt & Shorts Set, White & Navy",
      price: 690, badge: "New", badgeTone: "new",
      image: "https://www.bluesalon.com/cdn/shop/files/Moschino_Baby_White_T-Shirt_Navy_Logo_Shorts_Set_back_view_MOS124COM02720_1_540x.jpg?v=1777813096",
      cat: "Kids", type: "Baby", rating: 4.8, count: 12,
      color: "White", colorHex: "#eef0f2", sizes: ["6M", "12M", "18M", "24M"],
      images: ["https://www.bluesalon.com/cdn/shop/files/Moschino_Baby_White_T-Shirt_Navy_Logo_Shorts_Set_back_view_MOS124COM02720_1_540x.jpg?v=1777813096"],
      desc: "A soft cotton-jersey set for little ones — a white tee carrying the navy Moschino logo with coordinating logo shorts. Playful house branding, made for everyday comfort.",
      details: ["Cotton jersey", "Ribbed crew neck", "Elasticated waist shorts", "Machine washable", "Made in Italy"] },

    { id: "jules-juliette-paris-pyjama", vendor: "Jules & Juliette Paris", name: "Newborn PARIS Cotton Pyjama, Turquoise",
      price: 320,
      image: "https://www.bluesalon.com/cdn/shop/files/Jules_Juliette_Paris_New_Born_Boy_s_PARIS_Cotton_Pyjama_turquoise_back_view_PAR1210000-004_3_360x.jpg?v=1774965959",
      cat: "Kids", type: "Newborn", rating: 4.7, count: 8,
      color: "Turquoise", colorHex: "#3fb6c0", sizes: ["1M", "3M", "6M", "9M"],
      images: ["https://www.bluesalon.com/cdn/shop/files/Jules_Juliette_Paris_New_Born_Boy_s_PARIS_Cotton_Pyjama_turquoise_back_view_PAR1210000-004_3_360x.jpg?v=1774965959"],
      desc: "A pure-cotton newborn pyjama in soft turquoise, printed with the PARIS motif. Gentle on delicate skin, with a full popper opening for easy changes.",
      details: ["100% cotton", "Full-length popper fastening", "Ribbed cuffs", "Oeko-Tex certified", "Made in France"] },

    { id: "moschino-kids-logo-cap", vendor: "Moschino Kids", name: "Circular Logo Baseball Cap, Beige",
      price: 260,
      image: "https://www.bluesalon.com/cdn/shop/files/Moschino_Kids_Beige_Circular_Logo_Print_Baseball_Cap_side_right_view_MOS124ACC00363_5_360x.jpg?v=1777808022",
      cat: "Kids", type: "Accessories", rating: 4.6, count: 15,
      color: "Beige", colorHex: "#d8c7a8", sizes: ["One size"],
      images: ["https://www.bluesalon.com/cdn/shop/files/Moschino_Kids_Beige_Circular_Logo_Print_Baseball_Cap_side_right_view_MOS124ACC00363_5_360x.jpg?v=1777808022"],
      desc: "A beige cotton baseball cap stamped with the circular Moschino logo. An easy sun-ready finish for weekend dressing, with an adjustable back strap.",
      details: ["Cotton twill", "Circular logo print", "Curved brim", "Adjustable back strap", "Made in Italy"] },

    { id: "anandanies-smocked-dress", vendor: "Anandanies", name: "Hand-Smocked Cotton Dress, Rose",
      price: 450, badge: "New", badgeTone: "new",
      image: "https://www.bluesalon.com/cdn/shop/files/Anandanies_800x_crop_center.jpg?v=1779268779",
      cat: "Kids", type: "Girls", rating: 4.8, count: 6,
      color: "Rose", colorHex: "#e8b7c4", sizes: ["2Y", "4Y", "6Y", "8Y"],
      images: ["https://www.bluesalon.com/cdn/shop/files/Anandanies_800x_crop_center.jpg?v=1779268779"],
      desc: "A hand-smocked cotton dress in soft rose, finished with delicate embroidery. Handcrafted childrenswear made for celebrations and Sunday best.",
      details: ["100% cotton", "Hand-smocked bodice", "Embroidered detail", "Machine washable, gentle cycle", "Handmade"] },

    { id: "moschino-kids-teddy-tee", vendor: "Moschino Kids", name: "Teddy Bear Star Embroidery T-Shirt, Black",
      price: 320, badge: "Bestseller", badgeTone: "bestseller",
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/Moschino_Kid_Black_Cotton_T-Shirt_with_Star_Teddy_Bear_Embroidery_back_view_MOS124TOP04383_1_540x.jpg?v=1777822238",
      cat: "Kids", type: "Tops", rating: 4.8, count: 22,
      color: "Black", colorHex: "#16181c", sizes: ["4Y", "6Y", "8Y", "10Y", "12Y"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/Moschino_Kid_Black_Cotton_T-Shirt_with_Star_Teddy_Bear_Embroidery_back_view_MOS124TOP04383_1_540x.jpg?v=1777822238"],
      desc: "Black cotton jersey with the signature Teddy Bear cradling a star, embroidered at the back. A playful house icon on an everyday essential.",
      details: ["Cotton jersey", "Teddy Bear star embroidery", "Ribbed crew neck", "Machine washable", "Made in Italy"] },

    { id: "moschino-kids-logo-tee", vendor: "Moschino Kids", name: "Logo Print T-Shirt, Ivory",
      price: 300,
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/MOS124TOP04226_1_540x.jpg?v=1759405193",
      cat: "Kids", type: "Tops", rating: 4.6, count: 17,
      color: "Ivory", colorHex: "#efece6", sizes: ["4Y", "6Y", "8Y", "10Y", "12Y"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/MOS124TOP04226_1_540x.jpg?v=1759405193"],
      desc: "A soft ivory cotton tee finished with the Moschino logo. An easy layering piece that pairs with everything in the wardrobe.",
      details: ["Cotton jersey", "Front logo print", "Ribbed crew neck", "Machine washable", "Made in Italy"] },

    { id: "aigner-kids-qatar-tee", vendor: "Aigner Kids", name: "QATAR Print Horseshoe T-Shirt, Burgundy",
      price: 340, badge: "Exclusive", badgeTone: "gold",
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/Aigner_Kids_Burgundy_T-Shirt_with_QATAR_Print_and_Horseshoe_Pattern_AIG124TOP07552_1_540x.jpg?v=1761633004",
      cat: "Kids", type: "Tops", rating: 4.7, count: 9,
      color: "Burgundy", colorHex: "#6b1f2a", sizes: ["4Y", "6Y", "8Y", "10Y", "12Y"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/Aigner_Kids_Burgundy_T-Shirt_with_QATAR_Print_and_Horseshoe_Pattern_AIG124TOP07552_1_540x.jpg?v=1761633004"],
      desc: "Burgundy cotton tee with the Aigner horseshoe motif and a QATAR print — a local-edition piece from the house's kidswear line.",
      details: ["Cotton jersey", "Horseshoe pattern · QATAR print", "Ribbed crew neck", "Machine washable", "Made in Italy"] },

    { id: "polo-rl-kids-sneakers", vendor: "Polo Ralph Lauren Kids", name: "Boys' Sneakers, White & Green",
      price: 390, badge: "Buyer's Pick", badgeTone: "bestseller",
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/Polo_Ralph_Lauren_Kids_Boy_s_White_Green_Sneakers_RLF124FTW01313_1_540x.jpg?v=1760536058",
      cat: "Kids", type: "Footwear", rating: 4.8, count: 31,
      color: "White", colorHex: "#eef0f2", sizes: ["28", "30", "32", "34", "36"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/Polo_Ralph_Lauren_Kids_Boy_s_White_Green_Sneakers_RLF124FTW01313_1_540x.jpg?v=1760536058"],
      desc: "A crisp white low-top sneaker with green accents and the embroidered pony. Lace-up comfort for school days and weekends alike.",
      details: ["Canvas & leather upper", "Signature pony embroidery", "Lace-up fastening", "Rubber cupsole", "Wipe clean"] },

    { id: "missoni-kids-knit-sneaker-hi", vendor: "Missoni Kids", name: "Zigzag Knit Sneakers",
      price: 420, badge: "New", badgeTone: "new",
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/FR2214FTW00056_1_540x.jpg?v=1770620141",
      cat: "Kids", type: "Footwear", rating: 4.6, count: 12,
      color: "Multi", colorHex: "#c0623f", sizes: ["28", "30", "32", "34", "36"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/FR2214FTW00056_1_540x.jpg?v=1770620141"],
      desc: "The house zigzag rendered in a soft knit sneaker — colourful, lightweight and made to move. A signature Missoni finish for little feet.",
      details: ["Knit textile upper", "Zigzag pattern", "Elasticated lace detail", "Cushioned footbed", "Rubber sole"] },

    { id: "missoni-kids-knit-sneaker-lo", vendor: "Missoni Kids", name: "Low-Top Knit Sneakers",
      price: 410,
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/FR2214FTW00013_1_540x.jpg?v=1770619850",
      cat: "Kids", type: "Footwear", rating: 4.5, count: 10,
      color: "Multi", colorHex: "#5a7d8c", sizes: ["28", "30", "32", "34", "36"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/FR2214FTW00013_1_540x.jpg?v=1770619850"],
      desc: "A low-top knit sneaker in the signature Missoni weave — breathable, flexible and endlessly wearable through the season.",
      details: ["Knit textile upper", "Signature weave", "Lace-up fastening", "Cushioned footbed", "Rubber sole"] },

    { id: "loropiana-kids-beanie", vendor: "Loro Piana Kids", name: "Cashmere Knit Beanie, Camel",
      price: 480, badge: "Limited", badgeTone: "limited",
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00001_0_9040eabc-30ad-4c02-af89-952281946515_540x.jpg?v=1755508986",
      cat: "Kids", type: "Accessories", rating: 4.9, count: 8,
      color: "Camel", colorHex: "#cdb79e", sizes: ["One size"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00001_0_9040eabc-30ad-4c02-af89-952281946515_540x.jpg?v=1755508986"],
      desc: "A soft cashmere beanie in warm camel — feather-light warmth from the house synonymous with the world's finest fibres.",
      details: ["Pure cashmere", "Ribbed knit", "Turn-back cuff", "Dry clean", "Made in Italy"] },

    { id: "loropiana-kids-scarf", vendor: "Loro Piana Kids", name: "Cashmere Scarf, Ivory",
      price: 520,
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00013_0_540x.jpg?v=1755509682",
      cat: "Kids", type: "Accessories", rating: 4.9, count: 6,
      color: "Ivory", colorHex: "#efe9dc", sizes: ["One size"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00013_0_540x.jpg?v=1755509682"],
      desc: "An ivory cashmere scarf, impossibly soft and warm — an heirloom-quality finishing piece for cooler days.",
      details: ["Pure cashmere", "Fringed edges", "Lightweight warmth", "Dry clean", "Made in Italy"] },

    { id: "loropiana-kids-mittens", vendor: "Loro Piana Kids", name: "Knit Mittens, Grey",
      price: 360,
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00003_0_540x.jpg?v=1755509121",
      cat: "Kids", type: "Accessories", rating: 4.7, count: 5,
      color: "Grey", colorHex: "#b7bcc2", sizes: ["One size"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00003_0_540x.jpg?v=1755509121"],
      desc: "Grey cashmere-blend mittens on a connecting cord — warm little hands, kept together through the coldest days.",
      details: ["Cashmere blend", "Ribbed cuffs", "Connecting cord", "Dry clean", "Made in Italy"] },

    { id: "loropiana-kids-headband", vendor: "Loro Piana Kids", name: "Cashmere Headband, Rose",
      price: 320,
      image: "https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00008_0_540x.jpg?v=1755509452",
      cat: "Kids", type: "Accessories", rating: 4.8, count: 7,
      color: "Rose", colorHex: "#e8b7c4", sizes: ["One size"],
      images: ["https://cdn.shopify.com/s/files/1/0370/6444/1991/files/LOO124ACC00008_0_540x.jpg?v=1755509452"],
      desc: "A soft rose cashmere headband — cosy warmth with a delicate finish, gentle enough for the smallest heads.",
      details: ["Pure cashmere", "Ribbed knit", "Soft stretch fit", "Dry clean", "Made in Italy"] },
  ];

  const categories = [
    { label: "Women", img: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80" },
    { label: "Men", img: "https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=80" },
    { label: "Bags", img: img("Orlandi_Valentino_Women_s_Leather_Braided_Handle_Tote_burgundy_angled_side_POV123BAG00286_1_540x.webp") },
    { label: "Footwear", img: img("S2214700060002_02_540x.webp") },
    { label: "Beauty", img: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80" },
    { label: "Watches", img: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=80" },
    { label: "Luggage", img: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=80" },
    { label: "Gourmet", img: img("1782909937961.jpeg") },
  ];
  const nav = ["Women", "Men", "Kids", "Beauty", "Luggage", "Gourmet", "Home & Linen", "Gift"];
  return { products, categories, nav, hero: img("1_d90af013-05a4-447c-b48b-e2f61584c227_540x.webp") };
})();
